services:
  health:
    build:
      context: .
      dockerfile: docker/health.Dockerfile
    environment:
      - GRPC_PORT=50051
    ports:
      - "50051"

  gateway:
    build:
      context: .
      dockerfile: docker/gateway.Dockerfile
    environment:
      - HEALTH_SERVICE_ADDR=health:50051
    ports:
      - "8080:8080"
    depends_on:
      - health
