// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: common/proto/interbank.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InterbankService_InitiatePayment_FullMethodName = "/interbank.v1.InterbankService/InitiatePayment"
)

// InterbankServiceClient is the client API for InterbankService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InterbankServiceClient interface {
	InitiatePayment(ctx context.Context, in *InitiateInterbankPaymentRequest, opts ...grpc.CallOption) (*InitiateInterbankPaymentResponse, error)
}

type interbankServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInterbankServiceClient(cc grpc.ClientConnInterface) InterbankServiceClient {
	return &interbankServiceClient{cc}
}

func (c *interbankServiceClient) InitiatePayment(ctx context.Context, in *InitiateInterbankPaymentRequest, opts ...grpc.CallOption) (*InitiateInterbankPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateInterbankPaymentResponse)
	err := c.cc.Invoke(ctx, InterbankService_InitiatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InterbankServiceServer is the server API for InterbankService service.
// All implementations must embed UnimplementedInterbankServiceServer
// for forward compatibility.
type InterbankServiceServer interface {
	InitiatePayment(context.Context, *InitiateInterbankPaymentRequest) (*InitiateInterbankPaymentResponse, error)
	mustEmbedUnimplementedInterbankServiceServer()
}

// UnimplementedInterbankServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInterbankServiceServer struct{}

func (UnimplementedInterbankServiceServer) InitiatePayment(context.Context, *InitiateInterbankPaymentRequest) (*InitiateInterbankPaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiatePayment not implemented")
}
func (UnimplementedInterbankServiceServer) mustEmbedUnimplementedInterbankServiceServer() {}
func (UnimplementedInterbankServiceServer) testEmbeddedByValue()                          {}

// UnsafeInterbankServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InterbankServiceServer will
// result in compilation errors.
type UnsafeInterbankServiceServer interface {
	mustEmbedUnimplementedInterbankServiceServer()
}

func RegisterInterbankServiceServer(s grpc.ServiceRegistrar, srv InterbankServiceServer) {
	// If the following call panics, it indicates UnimplementedInterbankServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InterbankService_ServiceDesc, srv)
}

func _InterbankService_InitiatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateInterbankPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterbankServiceServer).InitiatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterbankService_InitiatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterbankServiceServer).InitiatePayment(ctx, req.(*InitiateInterbankPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InterbankService_ServiceDesc is the grpc.ServiceDesc for InterbankService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InterbankService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interbank.v1.InterbankService",
	HandlerType: (*InterbankServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiatePayment",
			Handler:    _InterbankService_InitiatePayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/proto/interbank.proto",
}
