// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: common/proto/interbank.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitiateInterbankPaymentRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PayerAccountNumber string                 `protobuf:"bytes,1,opt,name=payer_account_number,json=payerAccountNumber,proto3" json:"payer_account_number,omitempty"`
	PayeeAccountNumber string                 `protobuf:"bytes,2,opt,name=payee_account_number,json=payeeAccountNumber,proto3" json:"payee_account_number,omitempty"`
	Amount             float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency           string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	BankingTxId        uint64                 `protobuf:"varint,5,opt,name=banking_tx_id,json=bankingTxId,proto3" json:"banking_tx_id,omitempty"`
	Message            string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	PaymentCode        string                 `protobuf:"bytes,7,opt,name=payment_code,json=paymentCode,proto3" json:"payment_code,omitempty"`
	PaymentPurpose     string                 `protobuf:"bytes,8,opt,name=payment_purpose,json=paymentPurpose,proto3" json:"payment_purpose,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InitiateInterbankPaymentRequest) Reset() {
	*x = InitiateInterbankPaymentRequest{}
	mi := &file_common_proto_interbank_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateInterbankPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateInterbankPaymentRequest) ProtoMessage() {}

func (x *InitiateInterbankPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_interbank_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateInterbankPaymentRequest.ProtoReflect.Descriptor instead.
func (*InitiateInterbankPaymentRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_interbank_proto_rawDescGZIP(), []int{0}
}

func (x *InitiateInterbankPaymentRequest) GetPayerAccountNumber() string {
	if x != nil {
		return x.PayerAccountNumber
	}
	return ""
}

func (x *InitiateInterbankPaymentRequest) GetPayeeAccountNumber() string {
	if x != nil {
		return x.PayeeAccountNumber
	}
	return ""
}

func (x *InitiateInterbankPaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *InitiateInterbankPaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *InitiateInterbankPaymentRequest) GetBankingTxId() uint64 {
	if x != nil {
		return x.BankingTxId
	}
	return 0
}

func (x *InitiateInterbankPaymentRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InitiateInterbankPaymentRequest) GetPaymentCode() string {
	if x != nil {
		return x.PaymentCode
	}
	return ""
}

func (x *InitiateInterbankPaymentRequest) GetPaymentPurpose() string {
	if x != nil {
		return x.PaymentPurpose
	}
	return ""
}

type InitiateInterbankPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateInterbankPaymentResponse) Reset() {
	*x = InitiateInterbankPaymentResponse{}
	mi := &file_common_proto_interbank_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateInterbankPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateInterbankPaymentResponse) ProtoMessage() {}

func (x *InitiateInterbankPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_interbank_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateInterbankPaymentResponse.ProtoReflect.Descriptor instead.
func (*InitiateInterbankPaymentResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_interbank_proto_rawDescGZIP(), []int{1}
}

var File_common_proto_interbank_proto protoreflect.FileDescriptor

const file_common_proto_interbank_proto_rawDesc = "" +
	"\n" +
	"\x1ccommon/proto/interbank.proto\x12\finterbank.v1\"\xc3\x02\n" +
	"\x1fInitiateInterbankPaymentRequest\x120\n" +
	"\x14payer_account_number\x18\x01 \x01(\tR\x12payerAccountNumber\x120\n" +
	"\x14payee_account_number\x18\x02 \x01(\tR\x12payeeAccountNumber\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\"\n" +
	"\rbanking_tx_id\x18\x05 \x01(\x04R\vbankingTxId\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12!\n" +
	"\fpayment_code\x18\a \x01(\tR\vpaymentCode\x12'\n" +
	"\x0fpayment_purpose\x18\b \x01(\tR\x0epaymentPurpose\"\"\n" +
	" InitiateInterbankPaymentResponse2\x84\x01\n" +
	"\x10InterbankService\x12p\n" +
	"\x0fInitiatePayment\x12-.interbank.v1.InitiateInterbankPaymentRequest\x1a..interbank.v1.InitiateInterbankPaymentResponseB\x12Z\x10common/pkg/pb;pbb\x06proto3"

var (
	file_common_proto_interbank_proto_rawDescOnce sync.Once
	file_common_proto_interbank_proto_rawDescData []byte
)

func file_common_proto_interbank_proto_rawDescGZIP() []byte {
	file_common_proto_interbank_proto_rawDescOnce.Do(func() {
		file_common_proto_interbank_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_interbank_proto_rawDesc), len(file_common_proto_interbank_proto_rawDesc)))
	})
	return file_common_proto_interbank_proto_rawDescData
}

var file_common_proto_interbank_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_interbank_proto_goTypes = []any{
	(*InitiateInterbankPaymentRequest)(nil),  // 0: interbank.v1.InitiateInterbankPaymentRequest
	(*InitiateInterbankPaymentResponse)(nil), // 1: interbank.v1.InitiateInterbankPaymentResponse
}
var file_common_proto_interbank_proto_depIdxs = []int32{
	0, // 0: interbank.v1.InterbankService.InitiatePayment:input_type -> interbank.v1.InitiateInterbankPaymentRequest
	1, // 1: interbank.v1.InterbankService.InitiatePayment:output_type -> interbank.v1.InitiateInterbankPaymentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_interbank_proto_init() }
func file_common_proto_interbank_proto_init() {
	if File_common_proto_interbank_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_interbank_proto_rawDesc), len(file_common_proto_interbank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_interbank_proto_goTypes,
		DependencyIndexes: file_common_proto_interbank_proto_depIdxs,
		MessageInfos:      file_common_proto_interbank_proto_msgTypes,
	}.Build()
	File_common_proto_interbank_proto = out.File
	file_common_proto_interbank_proto_goTypes = nil
	file_common_proto_interbank_proto_depIdxs = nil
}
