// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: common/proto/trading.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TradingService_TransferFunds_FullMethodName        = "/trading.v1.TradingService/TransferFunds"
	TradingService_ListPublicStocks_FullMethodName     = "/trading.v1.TradingService/ListPublicStocks"
	TradingService_ReservePeerOtcShares_FullMethodName = "/trading.v1.TradingService/ReservePeerOtcShares"
	TradingService_ReleasePeerOtcShares_FullMethodName = "/trading.v1.TradingService/ReleasePeerOtcShares"
	TradingService_ConsumePeerOtcShares_FullMethodName = "/trading.v1.TradingService/ConsumePeerOtcShares"
	TradingService_CreditPeerOtcShares_FullMethodName  = "/trading.v1.TradingService/CreditPeerOtcShares"
)

// TradingServiceClient is the client API for TradingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TradingServiceClient interface {
	TransferFunds(ctx context.Context, in *TransferFundsRequest, opts ...grpc.CallOption) (*TransferFundsResponse, error)
	ListPublicStocks(ctx context.Context, in *ListPublicStocksRequest, opts ...grpc.CallOption) (*ListPublicStocksResponse, error)
	ReservePeerOtcShares(ctx context.Context, in *ReservePeerOtcSharesRequest, opts ...grpc.CallOption) (*PeerOtcSharesResponse, error)
	ReleasePeerOtcShares(ctx context.Context, in *ReleasePeerOtcSharesRequest, opts ...grpc.CallOption) (*PeerOtcSharesResponse, error)
	ConsumePeerOtcShares(ctx context.Context, in *ConsumePeerOtcSharesRequest, opts ...grpc.CallOption) (*PeerOtcSharesResponse, error)
	CreditPeerOtcShares(ctx context.Context, in *CreditPeerOtcSharesRequest, opts ...grpc.CallOption) (*PeerOtcSharesResponse, error)
}

type tradingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTradingServiceClient(cc grpc.ClientConnInterface) TradingServiceClient {
	return &tradingServiceClient{cc}
}

func (c *tradingServiceClient) TransferFunds(ctx context.Context, in *TransferFundsRequest, opts ...grpc.CallOption) (*TransferFundsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferFundsResponse)
	err := c.cc.Invoke(ctx, TradingService_TransferFunds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) ListPublicStocks(ctx context.Context, in *ListPublicStocksRequest, opts ...grpc.CallOption) (*ListPublicStocksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPublicStocksResponse)
	err := c.cc.Invoke(ctx, TradingService_ListPublicStocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) ReservePeerOtcShares(ctx context.Context, in *ReservePeerOtcSharesRequest, opts ...grpc.CallOption) (*PeerOtcSharesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerOtcSharesResponse)
	err := c.cc.Invoke(ctx, TradingService_ReservePeerOtcShares_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) ReleasePeerOtcShares(ctx context.Context, in *ReleasePeerOtcSharesRequest, opts ...grpc.CallOption) (*PeerOtcSharesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerOtcSharesResponse)
	err := c.cc.Invoke(ctx, TradingService_ReleasePeerOtcShares_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) ConsumePeerOtcShares(ctx context.Context, in *ConsumePeerOtcSharesRequest, opts ...grpc.CallOption) (*PeerOtcSharesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerOtcSharesResponse)
	err := c.cc.Invoke(ctx, TradingService_ConsumePeerOtcShares_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) CreditPeerOtcShares(ctx context.Context, in *CreditPeerOtcSharesRequest, opts ...grpc.CallOption) (*PeerOtcSharesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerOtcSharesResponse)
	err := c.cc.Invoke(ctx, TradingService_CreditPeerOtcShares_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradingServiceServer is the server API for TradingService service.
// All implementations must embed UnimplementedTradingServiceServer
// for forward compatibility.
type TradingServiceServer interface {
	TransferFunds(context.Context, *TransferFundsRequest) (*TransferFundsResponse, error)
	ListPublicStocks(context.Context, *ListPublicStocksRequest) (*ListPublicStocksResponse, error)
	ReservePeerOtcShares(context.Context, *ReservePeerOtcSharesRequest) (*PeerOtcSharesResponse, error)
	ReleasePeerOtcShares(context.Context, *ReleasePeerOtcSharesRequest) (*PeerOtcSharesResponse, error)
	ConsumePeerOtcShares(context.Context, *ConsumePeerOtcSharesRequest) (*PeerOtcSharesResponse, error)
	CreditPeerOtcShares(context.Context, *CreditPeerOtcSharesRequest) (*PeerOtcSharesResponse, error)
	mustEmbedUnimplementedTradingServiceServer()
}

// UnimplementedTradingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTradingServiceServer struct{}

func (UnimplementedTradingServiceServer) TransferFunds(context.Context, *TransferFundsRequest) (*TransferFundsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferFunds not implemented")
}
func (UnimplementedTradingServiceServer) ListPublicStocks(context.Context, *ListPublicStocksRequest) (*ListPublicStocksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPublicStocks not implemented")
}
func (UnimplementedTradingServiceServer) ReservePeerOtcShares(context.Context, *ReservePeerOtcSharesRequest) (*PeerOtcSharesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReservePeerOtcShares not implemented")
}
func (UnimplementedTradingServiceServer) ReleasePeerOtcShares(context.Context, *ReleasePeerOtcSharesRequest) (*PeerOtcSharesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleasePeerOtcShares not implemented")
}
func (UnimplementedTradingServiceServer) ConsumePeerOtcShares(context.Context, *ConsumePeerOtcSharesRequest) (*PeerOtcSharesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsumePeerOtcShares not implemented")
}
func (UnimplementedTradingServiceServer) CreditPeerOtcShares(context.Context, *CreditPeerOtcSharesRequest) (*PeerOtcSharesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreditPeerOtcShares not implemented")
}
func (UnimplementedTradingServiceServer) mustEmbedUnimplementedTradingServiceServer() {}
func (UnimplementedTradingServiceServer) testEmbeddedByValue()                        {}

// UnsafeTradingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradingServiceServer will
// result in compilation errors.
type UnsafeTradingServiceServer interface {
	mustEmbedUnimplementedTradingServiceServer()
}

func RegisterTradingServiceServer(s grpc.ServiceRegistrar, srv TradingServiceServer) {
	// If the following call panics, it indicates UnimplementedTradingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TradingService_ServiceDesc, srv)
}

func _TradingService_TransferFunds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferFundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).TransferFunds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_TransferFunds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).TransferFunds(ctx, req.(*TransferFundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_ListPublicStocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPublicStocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).ListPublicStocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_ListPublicStocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).ListPublicStocks(ctx, req.(*ListPublicStocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_ReservePeerOtcShares_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReservePeerOtcSharesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).ReservePeerOtcShares(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_ReservePeerOtcShares_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).ReservePeerOtcShares(ctx, req.(*ReservePeerOtcSharesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_ReleasePeerOtcShares_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleasePeerOtcSharesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).ReleasePeerOtcShares(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_ReleasePeerOtcShares_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).ReleasePeerOtcShares(ctx, req.(*ReleasePeerOtcSharesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_ConsumePeerOtcShares_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumePeerOtcSharesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).ConsumePeerOtcShares(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_ConsumePeerOtcShares_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).ConsumePeerOtcShares(ctx, req.(*ConsumePeerOtcSharesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_CreditPeerOtcShares_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreditPeerOtcSharesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).CreditPeerOtcShares(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_CreditPeerOtcShares_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).CreditPeerOtcShares(ctx, req.(*CreditPeerOtcSharesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TradingService_ServiceDesc is the grpc.ServiceDesc for TradingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TradingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trading.v1.TradingService",
	HandlerType: (*TradingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransferFunds",
			Handler:    _TradingService_TransferFunds_Handler,
		},
		{
			MethodName: "ListPublicStocks",
			Handler:    _TradingService_ListPublicStocks_Handler,
		},
		{
			MethodName: "ReservePeerOtcShares",
			Handler:    _TradingService_ReservePeerOtcShares_Handler,
		},
		{
			MethodName: "ReleasePeerOtcShares",
			Handler:    _TradingService_ReleasePeerOtcShares_Handler,
		},
		{
			MethodName: "ConsumePeerOtcShares",
			Handler:    _TradingService_ConsumePeerOtcShares_Handler,
		},
		{
			MethodName: "CreditPeerOtcShares",
			Handler:    _TradingService_CreditPeerOtcShares_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/proto/trading.proto",
}
