// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: common/proto/trading.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferFundsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromManagerId uint64                 `protobuf:"varint,1,opt,name=from_manager_id,json=fromManagerId,proto3" json:"from_manager_id,omitempty"`
	ToManagerId   uint64                 `protobuf:"varint,2,opt,name=to_manager_id,json=toManagerId,proto3" json:"to_manager_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferFundsRequest) Reset() {
	*x = TransferFundsRequest{}
	mi := &file_common_proto_trading_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferFundsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferFundsRequest) ProtoMessage() {}

func (x *TransferFundsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_trading_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferFundsRequest.ProtoReflect.Descriptor instead.
func (*TransferFundsRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_trading_proto_rawDescGZIP(), []int{0}
}

func (x *TransferFundsRequest) GetFromManagerId() uint64 {
	if x != nil {
		return x.FromManagerId
	}
	return 0
}

func (x *TransferFundsRequest) GetToManagerId() uint64 {
	if x != nil {
		return x.ToManagerId
	}
	return 0
}

type TransferFundsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FundsTransferred uint64                 `protobuf:"varint,1,opt,name=funds_transferred,json=fundsTransferred,proto3" json:"funds_transferred,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransferFundsResponse) Reset() {
	*x = TransferFundsResponse{}
	mi := &file_common_proto_trading_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferFundsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferFundsResponse) ProtoMessage() {}

func (x *TransferFundsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_trading_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferFundsResponse.ProtoReflect.Descriptor instead.
func (*TransferFundsResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_trading_proto_rawDescGZIP(), []int{1}
}

func (x *TransferFundsResponse) GetFundsTransferred() uint64 {
	if x != nil {
		return x.FundsTransferred
	}
	return 0
}

// ListPublicStocks returns every stock holding at this bank with a
// non-zero public_amount, grouped by ticker. Consumed by interbank-service
// to serve §3.1 GET /interbank/public-stock to peer banks.
type ListPublicStocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublicStocksRequest) Reset() {
	*x = ListPublicStocksRequest{}
	mi := &file_common_proto_trading_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublicStocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublicStocksRequest) ProtoMessage() {}

func (x *ListPublicStocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_trading_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublicStocksRequest.ProtoReflect.Descriptor instead.
func (*ListPublicStocksRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_trading_proto_rawDescGZIP(), []int{2}
}

type PublicStockSeller struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SellerId      uint64                 `protobuf:"varint,1,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicStockSeller) Reset() {
	*x = PublicStockSeller{}
	mi := &file_common_proto_trading_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicStockSeller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicStockSeller) ProtoMessage() {}

func (x *PublicStockSeller) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_trading_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicStockSeller.ProtoReflect.Descriptor instead.
func (*PublicStockSeller) Descriptor() ([]byte, []int) {
	return file_common_proto_trading_proto_rawDescGZIP(), []int{3}
}

func (x *PublicStockSeller) GetSellerId() uint64 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

func (x *PublicStockSeller) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PublicStockEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Sellers       []*PublicStockSeller   `protobuf:"bytes,2,rep,name=sellers,proto3" json:"sellers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicStockEntry) Reset() {
	*x = PublicStockEntry{}
	mi := &file_common_proto_trading_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicStockEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicStockEntry) ProtoMessage() {}

func (x *PublicStockEntry) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_trading_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicStockEntry.ProtoReflect.Descriptor instead.
func (*PublicStockEntry) Descriptor() ([]byte, []int) {
	return file_common_proto_trading_proto_rawDescGZIP(), []int{4}
}

func (x *PublicStockEntry) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *PublicStockEntry) GetSellers() []*PublicStockSeller {
	if x != nil {
		return x.Sellers
	}
	return nil
}

type ListPublicStocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stocks        []*PublicStockEntry    `protobuf:"bytes,1,rep,name=stocks,proto3" json:"stocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublicStocksResponse) Reset() {
	*x = ListPublicStocksResponse{}
	mi := &file_common_proto_trading_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublicStocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublicStocksResponse) ProtoMessage() {}

func (x *ListPublicStocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_trading_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublicStocksResponse.ProtoReflect.Descriptor instead.
func (*ListPublicStocksResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_trading_proto_rawDescGZIP(), []int{5}
}

func (x *ListPublicStocksResponse) GetStocks() []*PublicStockEntry {
	if x != nil {
		return x.Stocks
	}
	return nil
}

type ReservePeerOtcSharesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractId    string                 `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	SellerId      uint64                 `protobuf:"varint,2,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	Ticker        string                 `protobuf:"bytes,3,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservePeerOtcSharesRequest) Reset() {
	*x = ReservePeerOtcSharesRequest{}
	mi := &file_common_proto_trading_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservePeerOtcSharesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservePeerOtcSharesRequest) ProtoMessage() {}

func (x *ReservePeerOtcSharesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_trading_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservePeerOtcSharesRequest.ProtoReflect.Descriptor instead.
func (*ReservePeerOtcSharesRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_trading_proto_rawDescGZIP(), []int{6}
}

func (x *ReservePeerOtcSharesRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *ReservePeerOtcSharesRequest) GetSellerId() uint64 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

func (x *ReservePeerOtcSharesRequest) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *ReservePeerOtcSharesRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ReleasePeerOtcSharesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractId    string                 `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleasePeerOtcSharesRequest) Reset() {
	*x = ReleasePeerOtcSharesRequest{}
	mi := &file_common_proto_trading_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleasePeerOtcSharesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleasePeerOtcSharesRequest) ProtoMessage() {}

func (x *ReleasePeerOtcSharesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_trading_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleasePeerOtcSharesRequest.ProtoReflect.Descriptor instead.
func (*ReleasePeerOtcSharesRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_trading_proto_rawDescGZIP(), []int{7}
}

func (x *ReleasePeerOtcSharesRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

type ConsumePeerOtcSharesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractId    string                 `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumePeerOtcSharesRequest) Reset() {
	*x = ConsumePeerOtcSharesRequest{}
	mi := &file_common_proto_trading_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumePeerOtcSharesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumePeerOtcSharesRequest) ProtoMessage() {}

func (x *ConsumePeerOtcSharesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_trading_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumePeerOtcSharesRequest.ProtoReflect.Descriptor instead.
func (*ConsumePeerOtcSharesRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_trading_proto_rawDescGZIP(), []int{8}
}

func (x *ConsumePeerOtcSharesRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

type CreditPeerOtcSharesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractId      string                 `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	BuyerId         uint64                 `protobuf:"varint,2,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	Ticker          string                 `protobuf:"bytes,3,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Amount          float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PricePerUnitRsd float64                `protobuf:"fixed64,5,opt,name=price_per_unit_rsd,json=pricePerUnitRsd,proto3" json:"price_per_unit_rsd,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreditPeerOtcSharesRequest) Reset() {
	*x = CreditPeerOtcSharesRequest{}
	mi := &file_common_proto_trading_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditPeerOtcSharesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditPeerOtcSharesRequest) ProtoMessage() {}

func (x *CreditPeerOtcSharesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_trading_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditPeerOtcSharesRequest.ProtoReflect.Descriptor instead.
func (*CreditPeerOtcSharesRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_trading_proto_rawDescGZIP(), []int{9}
}

func (x *CreditPeerOtcSharesRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *CreditPeerOtcSharesRequest) GetBuyerId() uint64 {
	if x != nil {
		return x.BuyerId
	}
	return 0
}

func (x *CreditPeerOtcSharesRequest) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *CreditPeerOtcSharesRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreditPeerOtcSharesRequest) GetPricePerUnitRsd() float64 {
	if x != nil {
		return x.PricePerUnitRsd
	}
	return 0
}

type PeerOtcSharesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractId    string                 `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerOtcSharesResponse) Reset() {
	*x = PeerOtcSharesResponse{}
	mi := &file_common_proto_trading_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerOtcSharesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerOtcSharesResponse) ProtoMessage() {}

func (x *PeerOtcSharesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_trading_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerOtcSharesResponse.ProtoReflect.Descriptor instead.
func (*PeerOtcSharesResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_trading_proto_rawDescGZIP(), []int{10}
}

func (x *PeerOtcSharesResponse) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *PeerOtcSharesResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_common_proto_trading_proto protoreflect.FileDescriptor

const file_common_proto_trading_proto_rawDesc = "" +
	"\n" +
	"\x1acommon/proto/trading.proto\x12\n" +
	"trading.v1\"b\n" +
	"\x14TransferFundsRequest\x12&\n" +
	"\x0ffrom_manager_id\x18\x01 \x01(\x04R\rfromManagerId\x12\"\n" +
	"\rto_manager_id\x18\x02 \x01(\x04R\vtoManagerId\"D\n" +
	"\x15TransferFundsResponse\x12+\n" +
	"\x11funds_transferred\x18\x01 \x01(\x04R\x10fundsTransferred\"\x19\n" +
	"\x17ListPublicStocksRequest\"H\n" +
	"\x11PublicStockSeller\x12\x1b\n" +
	"\tseller_id\x18\x01 \x01(\x04R\bsellerId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"c\n" +
	"\x10PublicStockEntry\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\x127\n" +
	"\asellers\x18\x02 \x03(\v2\x1d.trading.v1.PublicStockSellerR\asellers\"P\n" +
	"\x18ListPublicStocksResponse\x124\n" +
	"\x06stocks\x18\x01 \x03(\v2\x1c.trading.v1.PublicStockEntryR\x06stocks\"\x8b\x01\n" +
	"\x1bReservePeerOtcSharesRequest\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12\x1b\n" +
	"\tseller_id\x18\x02 \x01(\x04R\bsellerId\x12\x16\n" +
	"\x06ticker\x18\x03 \x01(\tR\x06ticker\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\">\n" +
	"\x1bReleasePeerOtcSharesRequest\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\">\n" +
	"\x1bConsumePeerOtcSharesRequest\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\"\xb5\x01\n" +
	"\x1aCreditPeerOtcSharesRequest\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12\x19\n" +
	"\bbuyer_id\x18\x02 \x01(\x04R\abuyerId\x12\x16\n" +
	"\x06ticker\x18\x03 \x01(\tR\x06ticker\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12+\n" +
	"\x12price_per_unit_rsd\x18\x05 \x01(\x01R\x0fpricePerUnitRsd\"P\n" +
	"\x15PeerOtcSharesResponse\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xd3\x04\n" +
	"\x0eTradingService\x12T\n" +
	"\rTransferFunds\x12 .trading.v1.TransferFundsRequest\x1a!.trading.v1.TransferFundsResponse\x12]\n" +
	"\x10ListPublicStocks\x12#.trading.v1.ListPublicStocksRequest\x1a$.trading.v1.ListPublicStocksResponse\x12b\n" +
	"\x14ReservePeerOtcShares\x12'.trading.v1.ReservePeerOtcSharesRequest\x1a!.trading.v1.PeerOtcSharesResponse\x12b\n" +
	"\x14ReleasePeerOtcShares\x12'.trading.v1.ReleasePeerOtcSharesRequest\x1a!.trading.v1.PeerOtcSharesResponse\x12b\n" +
	"\x14ConsumePeerOtcShares\x12'.trading.v1.ConsumePeerOtcSharesRequest\x1a!.trading.v1.PeerOtcSharesResponse\x12`\n" +
	"\x13CreditPeerOtcShares\x12&.trading.v1.CreditPeerOtcSharesRequest\x1a!.trading.v1.PeerOtcSharesResponseB\x12Z\x10common/pkg/pb;pbb\x06proto3"

var (
	file_common_proto_trading_proto_rawDescOnce sync.Once
	file_common_proto_trading_proto_rawDescData []byte
)

func file_common_proto_trading_proto_rawDescGZIP() []byte {
	file_common_proto_trading_proto_rawDescOnce.Do(func() {
		file_common_proto_trading_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_trading_proto_rawDesc), len(file_common_proto_trading_proto_rawDesc)))
	})
	return file_common_proto_trading_proto_rawDescData
}

var file_common_proto_trading_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_common_proto_trading_proto_goTypes = []any{
	(*TransferFundsRequest)(nil),        // 0: trading.v1.TransferFundsRequest
	(*TransferFundsResponse)(nil),       // 1: trading.v1.TransferFundsResponse
	(*ListPublicStocksRequest)(nil),     // 2: trading.v1.ListPublicStocksRequest
	(*PublicStockSeller)(nil),           // 3: trading.v1.PublicStockSeller
	(*PublicStockEntry)(nil),            // 4: trading.v1.PublicStockEntry
	(*ListPublicStocksResponse)(nil),    // 5: trading.v1.ListPublicStocksResponse
	(*ReservePeerOtcSharesRequest)(nil), // 6: trading.v1.ReservePeerOtcSharesRequest
	(*ReleasePeerOtcSharesRequest)(nil), // 7: trading.v1.ReleasePeerOtcSharesRequest
	(*ConsumePeerOtcSharesRequest)(nil), // 8: trading.v1.ConsumePeerOtcSharesRequest
	(*CreditPeerOtcSharesRequest)(nil),  // 9: trading.v1.CreditPeerOtcSharesRequest
	(*PeerOtcSharesResponse)(nil),       // 10: trading.v1.PeerOtcSharesResponse
}
var file_common_proto_trading_proto_depIdxs = []int32{
	3,  // 0: trading.v1.PublicStockEntry.sellers:type_name -> trading.v1.PublicStockSeller
	4,  // 1: trading.v1.ListPublicStocksResponse.stocks:type_name -> trading.v1.PublicStockEntry
	0,  // 2: trading.v1.TradingService.TransferFunds:input_type -> trading.v1.TransferFundsRequest
	2,  // 3: trading.v1.TradingService.ListPublicStocks:input_type -> trading.v1.ListPublicStocksRequest
	6,  // 4: trading.v1.TradingService.ReservePeerOtcShares:input_type -> trading.v1.ReservePeerOtcSharesRequest
	7,  // 5: trading.v1.TradingService.ReleasePeerOtcShares:input_type -> trading.v1.ReleasePeerOtcSharesRequest
	8,  // 6: trading.v1.TradingService.ConsumePeerOtcShares:input_type -> trading.v1.ConsumePeerOtcSharesRequest
	9,  // 7: trading.v1.TradingService.CreditPeerOtcShares:input_type -> trading.v1.CreditPeerOtcSharesRequest
	1,  // 8: trading.v1.TradingService.TransferFunds:output_type -> trading.v1.TransferFundsResponse
	5,  // 9: trading.v1.TradingService.ListPublicStocks:output_type -> trading.v1.ListPublicStocksResponse
	10, // 10: trading.v1.TradingService.ReservePeerOtcShares:output_type -> trading.v1.PeerOtcSharesResponse
	10, // 11: trading.v1.TradingService.ReleasePeerOtcShares:output_type -> trading.v1.PeerOtcSharesResponse
	10, // 12: trading.v1.TradingService.ConsumePeerOtcShares:output_type -> trading.v1.PeerOtcSharesResponse
	10, // 13: trading.v1.TradingService.CreditPeerOtcShares:output_type -> trading.v1.PeerOtcSharesResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_common_proto_trading_proto_init() }
func file_common_proto_trading_proto_init() {
	if File_common_proto_trading_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_trading_proto_rawDesc), len(file_common_proto_trading_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_trading_proto_goTypes,
		DependencyIndexes: file_common_proto_trading_proto_depIdxs,
		MessageInfos:      file_common_proto_trading_proto_msgTypes,
	}.Build()
	File_common_proto_trading_proto = out.File
	file_common_proto_trading_proto_goTypes = nil
	file_common_proto_trading_proto_depIdxs = nil
}
