name: Banka 4 - CI
run-name: Checking if ${{ github.repository }} builds successfully

on:
  workflow_dispatch:
  #pull_request:
  pull_request_target:
    branches:
      - main

jobs:
  build-dev:
    runs-on: ubuntu-latest
    env:
      ENV: development
      COMPOSE_FILE: docker-compose-dev.yml

    steps:
    - name: Check out ${{ github.ref }} after a ${{ github.event_name }} event
      uses: actions/checkout@v5

    - name: Set up environment variables
      env:
        SECRETS_CONTEXT: ${{ toJson(secrets) }}
        VARS_CONTEXT: ${{ toJson(vars) }}
      run: |
        echo $SECRETS_CONTEXT | jq -r "to_entries|map(\"\(.key)=\\\"\(.value|tostring)\\\"\")|.[]" >> .env
        echo $VARS_CONTEXT | jq -r "to_entries|map(\"\(.key)=\\\"\(.value|tostring)\\\"\")|.[]" >> .env
        cat .env

    - name: Run the compose file
      run: docker compose -f ${{ env.COMPOSE_FILE }} up -d --build

    - name: Wait for the services to start up and check their health
      run: |
        while docker compose -f ${{ env.COMPOSE_FILE }} ps | grep "starting"; do
          sleep 5
        done
        if docker compose -f ${{ env.COMPOSE_FILE }} ps | grep "unhealthy"; then
          echo "One or more services are unhealthy. Check the logs for details."
          exit 1
        fi

    - name: Print running containers
      if: failure() || success()
      run: docker compose -f ${{ env.COMPOSE_FILE }} ps

    - name: Print container logs
      if: failure() || success()
      run: docker compose -f ${{ env.COMPOSE_FILE }} logs
        
    - name: Bring containers down
      if: failure() || success()
      run: docker compose -f ${{ env.COMPOSE_FILE }} down


  # build-prod:
  #   runs-on: ubuntu-latest
  #   environment: production
  #   steps: